/**
 * matcha — inject-rules.js
 * Lifecycle hooks for Claude Code and Codex.
 * Injects matcha philosophy before tasks.
 * Post-task snarky suggestions are AI-generated by the agent
 * (instructed via SKILL.md, not hardcoded here).
 */

import { getMatchaInstructions, getProjectConstraints } from "./matcha-instructions.js";

// ─── Hook handlers ─────────────────────────────────────────────────────────────

export async function preTask(event, context) {
  const instructions = getMatchaInstructions();
  const projectConstraints = getProjectConstraints();

  const projectSection = projectConstraints
    ? `
### 📋 Project Constraints (from MATCHA_PROJECT.md)
The following project-specific rules are ACTIVE. Follow them strictly:

${projectConstraints}
`
    : "";

  return {
    system_suffix: `
---
## Active Convention: matcha 🍵

You are operating under the matcha engineering philosophy.
Full ruleset injected below — follow it for every action in this session.

### 🔴 CRITICAL PLANNING GATE (ENFORCED BY HOOK)
You are BLOCKED from modifying files or running commands until you create/update the Intent Discovery plan in \`.agents/plan/current.md\`.
The hook will automatically allow execution once this file contains a valid Intent Discovery plan:
\`\`\`markdown
---
title: <task>
date: <date>
type: plan
status: active
---
# 🍵 Intent Discovery
- **Problem:** <problem description>
- **Goals:** <goals>
- **Success Criteria:** <success criteria>
\`\`\`
For every new task or major request, you MUST overwrite/update \`.agents/plan/current.md\` with the current task's details.

### Persistence of Intensity
If the user runs \`/matcha observe|enforce|audit\`, persist the change by writing \`{"intensity": "observe|enforce|audit"}\` to \`.agents/matcha-state.json\`.

At the END of every task response, include 3 matcha suggestions (match the user's conversation language, casual, direct, slightly sarcastic tone).
${projectSection}
${instructions}
---
`,
    metadata: { convention: "matcha", version: "2.5.25", event: event.type },
  };
}

// Default export for backward compat
export default async function handler(event, context) {
  if (event.type === "before:task" || event.type === "before:tool_use") {
    return preTask(event, context);
  }
  return null;
}
