/**
 * matcha — inject-rules.js
 * Lifecycle hooks for Claude Code and Codex.
 * Injects matcha philosophy before tasks.
 * Post-task snarky suggestions are AI-generated by the agent
 * (instructed via SKILL.md, not hardcoded here).
 */

import { getMatchaInstructions } from "./matcha-instructions.js";

// ─── Hook handlers ─────────────────────────────────────────────────────────────

export async function preTask(event, context) {
  const instructions = getMatchaInstructions();

  return {
    system_suffix: `
---
## Active Convention: matcha 🍵

You are operating under the matcha engineering philosophy.
Full ruleset injected below — follow it for every action in this session.
At the END of every task response, include 3 matcha suggestions (casual, direct, slightly sarcastic tone).

${instructions}
---
`,
    metadata: { convention: "matcha", version: "1.0.0", event: event.type },
  };
}

// Default export for backward compat
export default async function handler(event, context) {
  if (event.type === "before:task" || event.type === "before:tool_use") {
    return preTask(event, context);
  }
  return null;
}
